version: "3.3"
services: 
    web:
        build: .
        container_name: mvc-php
        volumes: 
            - .:/var/www/html
        ports: 
            - 8000:80
        depends_on: 
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: example
        